apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: {{ .Values.rec.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: redis-enterprise
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  nodes: {{ .Values.rec.nodes }}
  persistentSpec:
    enabled: {{ .Values.rec.persistentSpec.enabled }}
    volumeSize: {{ .Values.rec.persistentSpec.volumeSize }}
    {{- if .Values.rec.persistentSpec.storageClassName }}
    storageClassName: {{ .Values.rec.persistentSpec.storageClassName }}
    {{- end }}
  {{- if .Values.rec.redisEnterpriseNodeResources }}
  redisEnterpriseNodeResources:
    requests:
      cpu: {{ .Values.rec.redisEnterpriseNodeResources.requests.cpu | quote }}
      memory: {{ .Values.rec.redisEnterpriseNodeResources.requests.memory | quote }}
    limits:
      cpu: {{ .Values.rec.redisEnterpriseNodeResources.limits.cpu | quote }}
      memory: {{ .Values.rec.redisEnterpriseNodeResources.limits.memory | quote }}
  {{- end }}
  {{- if .Values.rec.bootstrapperImageSpec }}
  bootstrapperImageSpec:
    {{- toYaml .Values.rec.bootstrapperImageSpec | nindent 4 }}
  {{- end }}
  {{- if .Values.rec.redisEnterpriseServicesRiggerImageSpec }}
  redisEnterpriseServicesRiggerImageSpec:
    {{- toYaml .Values.rec.redisEnterpriseServicesRiggerImageSpec | nindent 4 }}
  {{- end }}
  {{- if .Values.rec.redisEnterpriseImageSpec }}
  redisEnterpriseImageSpec:
    {{- toYaml .Values.rec.redisEnterpriseImageSpec | nindent 4 }}
  {{- end }}
  {{- if .Values.rec.usageMeter }}
  usageMeter:
    {{- toYaml .Values.rec.usageMeter | nindent 4 }}
  {{- end }}
  {{- if .Values.rec.clusterCredentialSecretName }}
  clusterCredentialSecretName: {{ .Values.rec.clusterCredentialSecretName }}
  {{- end }}
  {{- if .Values.rec.licenseSecretName }}
  licenseSecretName: {{ .Values.rec.licenseSecretName }}
  {{- end }}
